baseURL = "https://kelly-chui.github.io/"
title = "Kelly Dev"
theme = "PaperMod"

defaultContentLanguage = "en"
languageCode = "en-us"

[pagination]
pagerSize = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[params]
defaultTheme = "auto"

[params.homeInfoParams]
Title = "Kelly Dev"
Content = "Blog home"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 2

[[menu.main]]
name = "About"
url = "/about/"
weight = 3

[markup]
[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNos = false
